const express = require('express')
const { SignupController, uploadimg } = require('../../Controller/UserController/SignupController')
const { MarkAttendenceMiddleware, MarkAttendenceRequest } = require('../../Controller/UserController/MarkAttendenceController')
const { LeaveRequestMiddleware, LeaveRequestData } = require('../../Controller/UserController/LeaveRequestController')
const { UserLoginController } = require('../../Controller/UserController/UserLoginController')
const { fetch_user_auth_middleware, fetch_user_specific_attendence } = require('../../Controller/UserController/FetchUserSpecificAttendence')
const { fetch_user_profileimage_middleware, fetch_user_profileimage_attendence } = require('../../Controller/UserController/FetchUserProfileImage')
const { FetchUserSpecificLeaveRequestMiddleware, FetchUserSpecificLeaveRequest } = require('../../Controller/UserController/FetchUserSpecificLeaveRequest')
const { UpdateUserProfileImageMiddleware , uploadimage , UpdateUserProfileImages } = require('../../Controller/UserController/UpdateUserProfileImage')
const { ViewReportMiddleware ,ViewReport } = require('../../Controller/UserController/UserViewReport')
const Userrouter = express.Router()

Userrouter.post('/Register', uploadimg.single("Imagepath"), SignupController)
Userrouter.post('/Mark/Attendence', MarkAttendenceMiddleware, MarkAttendenceRequest)
Userrouter.post('/Leave/Request', LeaveRequestMiddleware, LeaveRequestData)
Userrouter.post('/Login', UserLoginController)
Userrouter.get('/Fetch/specific/Attendence/:UserID', fetch_user_auth_middleware, fetch_user_specific_attendence)
Userrouter.get('/Fetch/Profile/Image/:UserID', fetch_user_profileimage_middleware, fetch_user_profileimage_attendence)
Userrouter.get('/Fetch/specific/Leave/Request/:UserID', FetchUserSpecificLeaveRequestMiddleware, FetchUserSpecificLeaveRequest)
Userrouter.put('/Update/Profile/Image', UpdateUserProfileImageMiddleware,uploadimage.single("Imagepath"), UpdateUserProfileImages)
Userrouter.get('/View/Report/:ID', ViewReportMiddleware, ViewReport )
module.exports = { Userrouter } 